import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';

export async function createPDFReport(sessionData, outputPath) {
    console.log('📄 Generating PDF report:', outputPath);

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs.createWriteStream(outputPath);

        doc.pipe(stream);

        // Header
        doc.fontSize(24).font('Helvetica-Bold').text('Meeting Report', { align: 'center' });
        doc.moveDown();

        doc.fontSize(12).font('Helvetica').text(`Title: ${sessionData.title}`);
        doc.text(`Date: ${new Date(sessionData.date).toLocaleString()}`);
        doc.text(`Duration: ${Math.floor(sessionData.duration / 60)} mins`);
        doc.text(`Category: ${sessionData.classification || 'Unclassified'}`);
        doc.moveDown();

        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        // Summary
        if (sessionData.summary) {
            doc.fontSize(16).font('Helvetica-Bold').text('Summary');
            doc.moveDown(0.5);
            doc.fontSize(11).font('Helvetica').text(sessionData.summary);
            doc.moveDown();
        }

        // Visual Insights
        if (sessionData.visuals && sessionData.visuals.length > 0) {
            doc.fontSize(16).font('Helvetica-Bold').text('Visual Insights (OCR)');
            doc.moveDown(0.5);
            sessionData.visuals.forEach((v, i) => {
                if (v.text) {
                    doc.fontSize(10).font('Helvetica-Bold').text(`Frame ${i + 1}:`);
                    doc.fontSize(9).font('Helvetica').text(v.text);
                    doc.moveDown(0.5);
                }
            });
            doc.moveDown();
        }

        // Transcript
        doc.fontSize(16).font('Helvetica-Bold').text('Transcript');
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica-Oblique').text(sessionData.transcript || 'No transcript available.');

        // Footer
        doc.moveTo(50, 750).lineTo(550, 750).stroke();
        doc.fontSize(10).text('Generated by MeetingAI', 50, 760, { align: 'center', width: 500 });

        doc.end();

        stream.on('finish', () => {
            resolve({ success: true, path: outputPath });
        });

        stream.on('error', (err) => {
            reject({ success: false, error: err.message });
        });
    });
}

export async function createDocxReport(sessionData, outputPath) {
    console.log('📄 Generating DOCX report:', outputPath);

    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                new Paragraph({
                    text: "Meeting Report",
                    heading: HeadingLevel.TITLE,
                    alignment: "center",
                }),
                new Paragraph({
                    children: [
                        new TextRun({ text: `Title: ${sessionData.title}`, bold: true }),
                    ],
                }),
                new Paragraph({
                    text: `Date: ${new Date(sessionData.date).toLocaleString()}`,
                }),
                new Paragraph({
                    text: `Duration: ${Math.floor(sessionData.duration / 60)} mins`,
                }),
                new Paragraph({
                    text: `Category: ${sessionData.classification || 'Unclassified'}`,
                }),
                new Paragraph({ text: "" }), // Spacing

                new Paragraph({
                    text: "Summary",
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({
                    text: sessionData.summary || "No summary available.",
                }),
                new Paragraph({ text: "" }), // Spacing

                ...(sessionData.visuals && sessionData.visuals.length > 0 ? [
                    new Paragraph({
                        text: "Visual Insights (OCR)",
                        heading: HeadingLevel.HEADING_1,
                    }),
                    ...sessionData.visuals.flatMap((v, i) => v.text ? [
                        new Paragraph({
                            children: [new TextRun({ text: `Frame ${i + 1}:`, bold: true })],
                        }),
                        new Paragraph({
                            text: v.text,
                        }),
                        new Paragraph({ text: "" }),
                    ] : [])
                ] : []),

                new Paragraph({
                    text: "Transcript",
                    heading: HeadingLevel.HEADING_1,
                }),
                new Paragraph({
                    text: sessionData.transcript || "No transcript available.",
                }),
            ],
        }],
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(outputPath, buffer);
    return { success: true, path: outputPath };
}
