import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export async function createPDFReport(sessionData, outputPath) {
    console.log('📄 Generating PDF report:', outputPath);

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs.createWriteStream(outputPath);

        doc.pipe(stream);

        // Header
        doc.fontSize(24).font('Helvetica-Bold').text('Meeting Report', { align: 'center' });
        doc.moveDown();

        doc.fontSize(12).font('Helvetica').text(`Title: ${sessionData.title}`);
        doc.text(`Date: ${new Date(sessionData.date).toLocaleString()}`);
        doc.text(`Duration: ${Math.floor(sessionData.duration / 60)} mins`);
        doc.text(`Category: ${sessionData.classification || 'Unclassified'}`);
        doc.moveDown();

        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown();

        // Summary
        if (sessionData.summary) {
            doc.fontSize(16).font('Helvetica-Bold').text('Summary');
            doc.moveDown(0.5);
            doc.fontSize(11).font('Helvetica').text(sessionData.summary);
            doc.moveDown();
        }

        // Action Items (Simple parsing simulation if not structured)
        doc.fontSize(16).font('Helvetica-Bold').text('Transcript');
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica-Oblique').text(sessionData.transcript || 'No transcript available.');

        // Footer
        doc.moveTo(50, 750).lineTo(550, 750).stroke();
        doc.fontSize(10).text('Generated by MeetingAI', 50, 760, { align: 'center', width: 500 });

        doc.end();

        stream.on('finish', () => {
            resolve({ success: true, path: outputPath });
        });

        stream.on('error', (err) => {
            reject({ success: false, error: err.message });
        });
    });
}
